name: AI Bot Handler - Manual Trigger

# 使用手动触发而不是 issue_comment
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to extract'
        required: true
        type: string
      category:
        description: 'Category (activity/conference/competition)'
        required: false
        type: choice
        options:
          - activity
          - conference
          - competition
        default: activity
      issue_number:
        description: 'Issue number to post comment to'
        required: true
        type: number

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  handle-bot-command:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/ai-bot/requirements.txt
      
      - name: Run AI Bot Handler
        id: handler
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MODELS_TOKEN: ${{ secrets.GH_MODELS_TOKEN }}
          BOT_URL: ${{ github.event.inputs.url }}
          BOT_CATEGORY: ${{ github.event.inputs.category }}
          BOT_ISSUE: ${{ github.event.inputs.issue_number }}
        run: |
          cd scripts/ai-bot
          python bot_handler_simple.py
      
      - name: Post result comment
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const outcome = '${{ steps.handler.outcome }}';
            const url = '${{ github.event.inputs.url }}';
            const category = '${{ github.event.inputs.category }}';
            
            let message = '';
            if (outcome === 'success') {
              message = `✅ **Bot 处理成功！**\n\n📝 **提取信息：**\n- URL: ${url}\n- 分类: ${category}\n\n查看工作流日志了解详细信息。`;
            } else {
              message = `❌ **Bot 处理失败**\n\n请检查：\n1. GH_MODELS_TOKEN 是否正确配置？\n2. URL 是否有效？\n3. 查看工作流日志了解详细错误。`;
            }
            
            github.rest.issues.createComment({
              issue_number: parseInt('${{ github.event.inputs.issue_number }}'),
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
