name: Auto Merge Bot PRs

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.head.ref, 'bot/')
    
    steps:
      - name: Approve and Merge PR
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            
            console.log(`PR #${pr.number} from branch: ${pr.head.ref}`);
            
            // 批准 PR
            try {
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                event: 'APPROVE'
              });
              console.log('✓ PR approved');
            } catch (e) {
              console.log('Already approved or error:', e.message);
            }
            
            // 等待一秒后合并
            await new Promise(resolve => setTimeout(resolve, 1000));
            
            // 合并 PR
            try {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash'
              });
              console.log('✓ PR merged successfully');
            } catch (e) {
              console.log('Could not merge:', e.message);
            }
